language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: panagiks
  password:
    secure: HsXRtBO/cn62WdwC2pvuqZ4RDgf9/1pLg/zg/gnfEt22vQf4Qjsf+q4mX8jGnT2XjvShJMaG1fVZGxNG7wdDaK9YV7lYH5hWH+yNTVIDO4vdFzcdccZxqvDHu30tf6ekLOlO6Cl5E1TWsWlya5CNW+lewq65qjxcHu+mF84H/4tvrdtEZ8LfEh3d5v6fjOAmfGglPn8JpAlBaTMsiNGrTPf8SeXuhmq6JxmxHRg5dWLECySW4r3bsVmR/8iLZvEf7FPhRbXqVFf3T0lLuTtrWGUb7DRMVIaJA6mwZ+rsOv6QnjyU1a1oKaAJvsamfXtuR4XqHdqLZLLk2MB2wfDLDnTrPj4WR2qVFZrmv2BJbw3w4z4LuPPWXejJIDmijp2Niu5G5DRHcvBacqMlGlDlafG0bdpMuWYuqQydc2ai1PoD2W51ikOgjI6U70w8QJ4ttbr60jW5ClMVujtuOZhrFWNtW362/VIsFyvFD4vC+TwHLSW3dyfWuHFBxOXOzzOrWZvBprQ7vmqdzkoytphCodoHZQ7dFwRyL3SXXGrGbyzbYdccvW7x/1SdLv3LoE7ZOgb32M6XCirFHZrmjr1Q885P7SPkvMTNQ8ghX0qbZTY3hAq9jfqv7bYO5zJmRsd5c5lDSy6iLWB1+ygUt/5/mdKCgRnJjJgw7+oKboBa5NE=
  on:
    tags: true
    repo: WCraaS/wcraas_common
    python: 3.7
