language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  twine_version: 2.0.0
  distributions: sdist bdist_wheel
  user: panagiks
  password:
    secure: LbnmcmWuBb+SWjq3D4dfKbfYlojC+qczS1n+0eJEGY1jZfYLr5M8fuMBaS92Kwec8TmYzimkLvGlCwxc2J9n3DKH+uae+T1MvnLJ69Tl1MFnsE1tuE1E2oZHHQfbFn7VYcCaaSBHKoTGzEpWdWa18yBCCdWZOFh9b4p10F76s2pVFnYrbl7yPG4IIwLvCQ/OgOsct4V1Dbx8TStjoyq9N3ljThMc7aWyq0Boy3D8qWEGT3O09xUjFw8vM1VGT2NeXXe1OYsw5xAG+owjDngyswMWwr18jYPOC5rq6KGhqT+dzrxg6PpE593ffHPKivY4pqSfcu8OkPwRkKL20Y7WYv/mS5RBFS2kuB2bqM+Pw249ajkbbcP6UTXLKeGr3wE8sqeGnBYjoxKksCaptWUi7JiDoUet6GXqOqsv4YvaqSqHbeJTf7lCRXAswtk4GrGfg14IXh8Q9YHe7hXA2jDHRaNHVRhL5j8zUaPpnhDzOrCXGKJzjfsEnDtp8EOKFucUSn8nHSxg6IgcxQdnifQQfIUWzt6/IiftD+wd7M5eL/BpYJxR6TGUgyLqfCLha1a+YJM5TcCIJzKcav2JSRMdCnfcusaT0KLVVpxsVnTwo6sLBfdFP1v+261tJnjV77nvGAW4Atqnfm090UM00YXXjthPpWgl/HuTmjCEyQ6EEGo=
  on:
    tags: true
    repo: WCraaS/wcraas_common
    python: 3.7
