language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  twine_version: 1.15.0
  distributions: sdist bdist_wheel
  user: panagiks
  password:
    secure: Kv9trReJgVMJfkT/SdY250teqVckHjApEMRu4dhz04X5U8NEoEdUrj5fT/EqCxgXxhW3QvT9F/2y42qXAwa3LyC4zfSEC4xhNSfjXDuRud482WUViK8uNt5wL7qAhuF/DqO/wWYouAvevHnBXGa8snZYh1p8sGcb3Ey+cuFySJ19AeF9KR/RhoIqJkfzjogM2kC4bq/lKeJ5p8uz1GSS0CbeyWjtSG9pt4von1htHpGo3g02QsJMca4oRBgiacI++yZcJKIdjCJADfMgJ6XH3cuy8aruWjPRlYSIKJxUc6aL6bxw+nGkbEMnyYaPVyJGL1PkXi/v0hgf1sCfSnoXFXwOgy6qLO7l/QsNhhBTLIMhpvTChOQPXWsm30wSMpLHzDFw2KA7Hf2T7sXIHEW6uT3mTYcc4XpKRtdTewEPm1F3kPOTHspzEwNa97wFu9xTtpQejEkVxvoYHyOFisDverYUy9ojTPQ8L/LNHp/AwTSYbFLpmEZNTikY6tLT1cCNzJQl17ACEAvjzmGcX4j+fzDlo7MYSg9xhk3iTOsBg5L6OnJXzhpTGz3n8zVfWmx8Ecwrwh6YW7elPCY5KMwfTVWsHLnaw/wnf2kEPKJTpkB+VUbfl7idy2SXRqwVBi+herVuK6JxlvE/Lr6WqhV/t+tiYmjs8C9NbqfHdnEsYGQ=
  on:
    tags: true
    repo: WCraaS/wcraas_common
    python: 3.6
